name: Update documentation CHANGELOG

on:
  push:
    branches: [ master ]
    paths:
      - CHANGELOG.md
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout website repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CHANGELOG_KEY }}
        repository: owenvoke/changelog-test
        path: pestphp-website
    - name: Copy CHANGELOG to website repository
      run: cp CHANGELOG.md pestphp-website/source/docs/changelog.md
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
          token: ${{ secrets.CHANGELOG_KEY }}
          commit-message: Update changelog.md
          committer: GitHub Action <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Update changelog.md'
          path: ./pestphp-website
